/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrismComp: typeof import('./src/components/PrismComp.vue')['default']
    ShikiComp: typeof import('./src/components/ShikiComp.vue')['default']
  }
}
